project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: ../index.ipynb
      title: Dashboard 
  code-links:
    - text: Codigo de importacion de datos
      icon: file-code
      href: ../collect.py
    - repo
    - binder

format:
  html:
    comments:
      giscus: 
        repo: sociest/sociest.org
        language: es
  #docx: default
  #jats: default

  # (other formats)
  pdf: default

execute:
  freeze: true



